services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python ingest/crawl_web.py
      python ingest/parse_pdfs.py
      python index/embed_documents.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: HF_HOME
        value: /tmp/huggingface
    autoDeploy: true
    region: oregon
    rootDir: backend