services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      export HF_HOME=/tmp/huggingface
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"
      python ingest/crawl_web.py
      python ingest/parse_pdfs.py
      python index/embed_documents.py
    envVars:
      - key: HF_HOME
        value: /tmp/huggingface
    autoDeploy: true
    region: oregon
    rootDir: backend